---
vault_addr: "https://vault.bevz.net"

vault_jwt_auth_path: "jwt"
vault_jwt_gitlab_url: "https://gitlab.bevz.net"

vault_ci_policy_name: "ci-cosign"
vault_ci_jwt_role_name: "ci-cosign"
vault_ci_project_path: "abevz/democicd"
