-- ============================================================
-- Use the per-node files instead of this generic index:
--   ch-1 -> 01_create_shard_databases_ch1.sql
--   ch-2 -> 01_create_shard_databases_ch2.sql
--   ch-3 -> 01_create_shard_databases_ch3.sql
--
-- Each ClickHouse node hosts two shard databases.
-- Do not run one active DDL file on every node.
-- ============================================================
