-- ============================================================
-- Use the per-node files instead of this generic index:
--   ch-1 -> 02_create_local_tables_ch1.sql
--   ch-2 -> 02_create_local_tables_ch2.sql
--   ch-3 -> 02_create_local_tables_ch3.sql
--
-- {shard01}/{replica01} are the local primary shard/replica macros.
-- {shard02}/{replica02} are the local secondary shard/replica macros.
-- ============================================================
