-- ============================================================
-- Use the per-node files instead of this generic index:
--   ch-1 -> 03_create_materialized_views_ch1.sql
--   ch-2 -> 03_create_materialized_views_ch2.sql
--   ch-3 -> 03_create_materialized_views_ch3.sql
--
-- Materialized views must exist only for the shard databases
-- hosted by the target node.
-- ============================================================
