package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"strconv"
	"strings"
	"sync"
	"time"
)

type config struct {
	host              string
	port              int
	user              string
	passwordFile      string
	secure            bool
	acceptInvalidCert bool
	workers           int
	rowsPerWorker     int
	sensorsPerWorker  int
	sensorBase        int
}

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	cfg := parseFlags()
	if err := run(ctx, cfg); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func parseFlags() config {
	cfg := config{}
	flag.StringVar(&cfg.host, "host", "ch-1", "ClickHouse host")
	flag.IntVar(&cfg.port, "port", 9440, "ClickHouse native TCP port")
	flag.StringVar(&cfg.user, "user", "admin", "ClickHouse user")
	flag.StringVar(&cfg.passwordFile, "password-file", os.ExpandEnv("$HOME/.clickhouse_admin_password"), "file containing ClickHouse password")
	flag.BoolVar(&cfg.secure, "secure", true, "use secure native TCP")
	flag.BoolVar(&cfg.acceptInvalidCert, "accept-invalid-certificate", true, "accept self-signed TLS certificate")
	flag.IntVar(&cfg.workers, "workers", 4, "parallel insert workers")
	flag.IntVar(&cfg.rowsPerWorker, "rows-per-worker", 250000, "rows inserted by each worker")
	flag.IntVar(&cfg.sensorsPerWorker, "sensors-per-worker", 25000, "distinct sensors generated by each worker")
	flag.IntVar(&cfg.sensorBase, "sensor-base", 200000, "first benchmark sensor id")
	flag.Parse()
	return cfg
}

func run(ctx context.Context, cfg config) error {
	if cfg.workers <= 0 {
		return errors.New("workers must be > 0")
	}
	if cfg.rowsPerWorker <= 0 {
		return errors.New("rows-per-worker must be > 0")
	}
	if cfg.sensorsPerWorker <= 0 {
		return errors.New("sensors-per-worker must be > 0")
	}

	password, err := readPassword(cfg.passwordFile)
	if err != nil {
		return err
	}

	runID := time.Now().UTC().Format("20060102_150405")
	fmt.Printf("run_id=%s workers=%d rows_per_worker=%d total_rows=%d\n",
		runID, cfg.workers, cfg.rowsPerWorker, cfg.workers*cfg.rowsPerWorker)

	start := time.Now()
	if err := runParallelInserts(ctx, cfg, password, runID); err != nil {
		return err
	}
	insertElapsed := time.Since(start)
	fmt.Printf("insert_elapsed_ms=%d insert_rows_per_sec=%.2f\n",
		insertElapsed.Milliseconds(), float64(cfg.workers*cfg.rowsPerWorker)/insertElapsed.Seconds())

	if err := clickhouse(ctx, cfg, password, "", "SYSTEM FLUSH DISTRIBUTED demo.sensor_readings_write"); err != nil {
		return err
	}

	selectID := "go_bench_select_" + runID
	selectQuery := fmt.Sprintf(`
SELECT
    count() AS rows,
    uniqExact(sensor_id) AS sensors,
    avg(value) AS avg_value
FROM demo.sensor_readings
WHERE sensor_id >= %d
  AND sensor_id < %d
`, cfg.sensorBase, cfg.sensorBase+cfg.workers*cfg.sensorsPerWorker)

	start = time.Now()
	if err := clickhouse(ctx, cfg, password, selectID, selectQuery); err != nil {
		return err
	}
	selectElapsed := time.Since(start)
	fmt.Printf("select_elapsed_ms=%d\n", selectElapsed.Milliseconds())

	if err := clickhouse(ctx, cfg, password, "", "SYSTEM FLUSH LOGS"); err != nil {
		return err
	}

	reportQuery := fmt.Sprintf(`
SELECT
    query_id,
    query_duration_ms,
    read_rows,
    read_bytes,
    written_rows,
    written_bytes,
    memory_usage
FROM system.query_log
WHERE startsWith(query_id, 'go_bench_insert_%[1]s')
   OR query_id = 'go_bench_select_%[1]s'
ORDER BY event_time_microseconds
FORMAT PrettyCompact
`, runID)

	return clickhouse(ctx, cfg, password, "", reportQuery)
}

func runParallelInserts(ctx context.Context, cfg config, password, runID string) error {
	errs := make(chan error, cfg.workers)
	var wg sync.WaitGroup

	for worker := 0; worker < cfg.workers; worker++ {
		worker := worker
		wg.Add(1)
		go func() {
			defer wg.Done()
			queryID := "go_bench_insert_" + runID + "_w" + strconv.Itoa(worker)
			sensorBase := cfg.sensorBase + worker*cfg.sensorsPerWorker
			query := insertQuery(sensorBase, cfg.sensorsPerWorker, cfg.rowsPerWorker)
			errs <- clickhouse(ctx, cfg, password, queryID, query)
		}()
	}

	wg.Wait()
	close(errs)

	var failures []string
	for err := range errs {
		if err != nil {
			failures = append(failures, err.Error())
		}
	}
	if len(failures) > 0 {
		return errors.New(strings.Join(failures, "\n"))
	}
	return nil
}

func insertQuery(sensorBase, sensors, rows int) string {
	return fmt.Sprintf(`
INSERT INTO demo.sensor_readings_write
SELECT
    %[1]d + (number %% %[2]d) AS sensor_id,
    toDate(ts) AS dt,
    ts,
    round(100 + (number %% %[2]d) / 1000.0 + rand() / 1e8, 2) AS value,
    1 AS version,
    now()
FROM (
    SELECT
        number,
        toDateTime('2025-03-01 00:00:00') + INTERVAL intDiv(number, %[2]d)*900 SECOND AS ts
    FROM numbers(%[3]d)
)
`, sensorBase, sensors, rows)
}

func clickhouse(ctx context.Context, cfg config, password, queryID, query string) error {
	args := []string{
		"--host", cfg.host,
		"--port", strconv.Itoa(cfg.port),
		"--user", cfg.user,
		"--password", password,
	}
	if cfg.secure {
		args = append(args, "--secure")
	}
	if cfg.acceptInvalidCert {
		args = append(args, "--accept-invalid-certificate")
	}
	if queryID != "" {
		args = append(args, "--query_id", queryID)
	}
	args = append(args, "--query", query)

	cmd := exec.CommandContext(ctx, "clickhouse-client", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func readPassword(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read password file %s: %w", path, err)
	}
	return strings.TrimSpace(string(data)), nil
}
