---
- name: Set target External Secrets Operator version
  ansible.builtin.set_fact:
    external_secrets_target_version: >-
      {{ requested_version | default(external_secrets_chart_version) }}

- name: Add External Secrets Helm repository
  kubernetes.core.helm_repository:
    name: external-secrets
    repo_url: "{{ external_secrets_helm_repo_url }}"
    state: present

- name: Install/Remove External Secrets Operator
  kubernetes.core.helm:
    name: "{{ external_secrets_release_name }}"
    chart_ref: "{{ external_secrets_chart_ref }}"
    chart_version: "{{ external_secrets_target_version }}"
    release_namespace: "{{ external_secrets_namespace }}"
    create_namespace: "{{ addon_state == 'present' }}"
    release_state: "{{ addon_state }}"
    wait: true
    timeout: "{{ external_secrets_wait_timeout }}"
    values:
      installCRDs: "{{ external_secrets_install_crds }}"

- name: Display result
  ansible.builtin.debug:
    msg: "External Secrets Operator ({{ addon_state }}) complete."
